- title: Media Development
  thumbnail: media_development.png
  url: /pages/media_development.html

- title: Web Development
  thumbnail: web_development.png
  url: /pages/web_development.html

- title: Software Training
  thumbnail: software_training.png
  url: /pages/software_training.html

- title: Performance Support
  thumbnail: performance_support.png
  url: /pages/performance_support.html

- title: Usability Testing
  thumbnail: usability_testing.png
  url: /pages/usability_testing.html

- title: Mobile Development
  thumbnail: mobile_development.png
  url: /pages/mobile_development.html 

- title: Instructor Guides
  thumbnail: instructor_guide.png
  url: /pages/instructor_guides.html

- title: SCORM Programming
  thumbnail: scorm_programming.png
  url: /pages/scorm_programming.html

- title: Curriculum Planning
  thumbnail: curriculum_planning.png
  url: /pages/curriculum_planning.html
