- title: eLearning
  thumbnail: software_training.png
  url: /pages/elearning.html

- title: Web Development
  thumbnail: web_development.png
  url: /pages/web_development.html

- title: Instructional Design
  thumbnail: curriculum_planning.png
  url: /pages/instructional_design.html

- title: System Administration
  thumbnail: system_administration.png
  url: /pages/system_administration.html

- title: Technical Writing
  thumbnail: scorm_programming.png
  url: /pages/technical_writing.html

- title: Information Architecture
  thumbnail: information_architecture.png
  url: /pages/information_architecture.html

- title: Usability Testing
  thumbnail: usability_testing.png
  url: /pages/usability_testing.html

- title: Media Development
  thumbnail: media_development.png
  url: /pages/media_development.html

- title: Mobile Development
  thumbnail: mobile_development.png
  url: /pages/mobile_development.html 